services:
  chatbot-app:
    build:
      context: ../
      dockerfile: src/Dockerfile
    container_name: chatbot-app
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true